version: '3.8'

services:
  cargodb:
    image: postgres:14
    container_name: postgres-cargo
    env_file:
      - ./.env
    volumes:
      - cargo_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  web:
    build: .
    container_name: web-cargo
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000


volumes:
  cargo_db:
    external: True